-- ================================================
-- FOODYA DATABASE SEED DATA FOR SUPABASE
-- ================================================
-- Password: SecurePass123!
-- BCrypt: $2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi
-- ================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ================================================
-- USERS (4 accounts: ADMIN, MERCHANT, DELIVERY, CUSTOMER)
-- Username pattern: ^[a-zA-Z0-9_-]+$ (letters, numbers, underscore, hyphen only)
-- ================================================

INSERT INTO users (
    id,
    username,
    email,
    password,
    full_name,
    phone_number,
    role,
    is_active,
    is_email_verified,
    is_phone_number_verified,
    account_locked,
    created_at,
    updated_at
) VALUES
-- ADMIN
(
    gen_random_uuid(),
    'admin_test01',
    'admin.test01@example.com',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Admin Test User',
    '+84900000001',
    'ADMIN',
    true,
    true,
    true,
    false,
    NOW(),
    NOW()
),
-- MERCHANT
(
    gen_random_uuid(),
    'merchant_test01',
    'merchant.test01@example.com',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Merchant Test User',
    '+84901000001',
    'MERCHANT',
    true,
    true,
    true,
    false,
    NOW(),
    NOW()
),
-- DELIVERY
(
    gen_random_uuid(),
    'delivery_test01',
    'delivery.test01@example.com',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Delivery Test User',
    '+84903000001',
    'DELIVERY',
    true,
    true,
    true,
    false,
    NOW(),
    NOW()
),
-- CUSTOMER
(
    gen_random_uuid(),
    'customer_test01',
    'customer.test01@example.com',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Customer Test User',
    '+84902000001',
    'CUSTOMER',
    true,
    true,
    true,
    false,
    NOW(),
    NOW()
);

-- ================================================
-- RESTAURANTS (5 restaurants owned by merchant_test01)
-- ================================================

INSERT INTO restaurants (
    id,
    name,
    address,
    phone_number,
    description,
    cuisine,
    rating,
    total_reviews,
    is_open,
    is_active,
    opening_time,
    closing_time,
    delivery_fee,
    estimated_delivery_time,
    owner_id,
    created_at,
    updated_at
) VALUES
-- Restaurant 1: Vietnamese
(
    gen_random_uuid(),
    'Pho Saigon 24h',
    '123 Nguyen Hue, Quan 1, TP.HCM',
    '+84281234001',
    'Authentic Vietnamese pho available 24/7',
    'Vietnamese',
    4.8,
    245,
    true,
    true,
    '00:00:00',
    '23:59:59',
    1.50,
    25,
    (SELECT id FROM users WHERE username = 'merchant_test01'),
    NOW(),
    NOW()
),
-- Restaurant 2: Japanese
(
    gen_random_uuid(),
    'Tokyo Sushi Bar',
    '456 Le Loi, Quan 3, TP.HCM',
    '+84281234002',
    'Fresh sushi and sashimi by Japanese chef',
    'Japanese',
    4.7,
    189,
    true,
    true,
    '11:00:00',
    '22:30:00',
    3.00,
    35,
    (SELECT id FROM users WHERE username = 'merchant_test01'),
    NOW(),
    NOW()
),
-- Restaurant 3: Korean
(
    gen_random_uuid(),
    'Seoul BBQ House',
    '789 Pasteur, Quan 1, TP.HCM',
    '+84281234003',
    'All-you-can-eat Korean BBQ',
    'Korean',
    4.6,
    156,
    true,
    true,
    '11:00:00',
    '23:00:00',
    2.50,
    30,
    (SELECT id FROM users WHERE username = 'merchant_test01'),
    NOW(),
    NOW()
),
-- Restaurant 4: Italian
(
    gen_random_uuid(),
    'Bella Napoli',
    '321 Hai Ba Trung, Quan 1, TP.HCM',
    '+84281234004',
    'Wood-fired pizza and homemade pasta',
    'Italian',
    4.9,
    312,
    true,
    true,
    '10:00:00',
    '22:00:00',
    2.00,
    30,
    (SELECT id FROM users WHERE username = 'merchant_test01'),
    NOW(),
    NOW()
),
-- Restaurant 5: American
(
    gen_random_uuid(),
    'Burger Paradise',
    '555 Nguyen Thi Minh Khai, Quan 1, TP.HCM',
    '+84281234005',
    'Gourmet burgers and American classics',
    'American',
    4.5,
    223,
    true,
    true,
    '10:00:00',
    '23:00:00',
    2.50,
    25,
    (SELECT id FROM users WHERE username = 'merchant_test01'),
    NOW(),
    NOW()
);

-- ================================================
-- MENU ITEMS (3 items per restaurant = 15 items)
-- Category must be: Appetizer, Main Course, Dessert, Beverage, Side Dish
-- ================================================

-- Pho Saigon 24h Menu
INSERT INTO menu_items (
    id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    category,
    preparation_time,
    calories,
    is_vegetarian,
    is_vegan,
    is_gluten_free,
    is_spicy,
    is_available,
    is_active,
    order_count,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Pho Saigon 24h'),
    'Pho Bo Tai',
    'Traditional beef pho with rare beef slices, rice noodles and fresh herbs',
    8.99,
    'https://images.unsplash.com/photo-1591814468924-caf88d1232e1',
    'Main Course',
    12,
    550,
    false,
    false,
    true,
    false,
    true,
    true,
    456,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Pho Saigon 24h'),
    'Goi Cuon',
    'Fresh spring rolls with shrimp, pork and vegetables',
    5.50,
    'https://images.unsplash.com/photo-1559847844-5315695dadae',
    'Appetizer',
    10,
    180,
    false,
    false,
    true,
    false,
    true,
    true,
    324,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Pho Saigon 24h'),
    'Tra Da Chanh',
    'Vietnamese iced lemon tea',
    2.50,
    'https://images.unsplash.com/photo-1556679343-c7306c1976bc',
    'Beverage',
    3,
    50,
    true,
    true,
    true,
    false,
    true,
    true,
    567,
    NOW(),
    NOW()
);

-- Tokyo Sushi Bar Menu
INSERT INTO menu_items (
    id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    category,
    preparation_time,
    calories,
    is_vegetarian,
    is_vegan,
    is_gluten_free,
    is_spicy,
    is_available,
    is_active,
    order_count,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Tokyo Sushi Bar'),
    'Salmon Nigiri Set',
    'Fresh salmon nigiri sushi - 8 pieces',
    16.99,
    'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351',
    'Main Course',
    12,
    480,
    false,
    false,
    true,
    false,
    true,
    true,
    389,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Tokyo Sushi Bar'),
    'Miso Soup',
    'Traditional Japanese soybean soup',
    3.99,
    'https://images.unsplash.com/photo-1606491048989-a5d2a2b9a686',
    'Appetizer',
    5,
    80,
    true,
    true,
    true,
    false,
    true,
    true,
    512,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Tokyo Sushi Bar'),
    'Matcha Ice Cream',
    'Japanese green tea ice cream',
    5.50,
    'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    'Dessert',
    2,
    220,
    true,
    false,
    true,
    false,
    true,
    true,
    298,
    NOW(),
    NOW()
);

-- Seoul BBQ House Menu
INSERT INTO menu_items (
    id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    category,
    preparation_time,
    calories,
    is_vegetarian,
    is_vegan,
    is_gluten_free,
    is_spicy,
    is_available,
    is_active,
    order_count,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Seoul BBQ House'),
    'Bulgogi',
    'Marinated grilled beef with vegetables and rice',
    15.99,
    'https://images.unsplash.com/photo-1590301157890-4810ed352733',
    'Main Course',
    18,
    680,
    false,
    false,
    true,
    false,
    true,
    true,
    445,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Seoul BBQ House'),
    'Kimchi',
    'Traditional fermented spicy cabbage',
    4.50,
    'https://images.unsplash.com/photo-1604908177453-7462950a6a3f',
    'Side Dish',
    2,
    35,
    true,
    true,
    true,
    true,
    true,
    true,
    623,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Seoul BBQ House'),
    'Soju',
    'Korean rice wine',
    8.99,
    'https://images.unsplash.com/photo-1514361892635-6b07e31e75f9',
    'Beverage',
    1,
    120,
    true,
    true,
    true,
    false,
    true,
    true,
    356,
    NOW(),
    NOW()
);

-- Bella Napoli Menu
INSERT INTO menu_items (
    id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    category,
    preparation_time,
    calories,
    is_vegetarian,
    is_vegan,
    is_gluten_free,
    is_spicy,
    is_available,
    is_active,
    order_count,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Bella Napoli'),
    'Margherita Pizza',
    'Classic Italian pizza with San Marzano tomatoes, mozzarella and basil',
    12.99,
    'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
    'Main Course',
    15,
    850,
    true,
    false,
    false,
    false,
    true,
    true,
    678,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Bella Napoli'),
    'Bruschetta',
    'Toasted bread with fresh tomatoes, garlic and basil',
    7.50,
    'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f',
    'Appetizer',
    10,
    280,
    true,
    true,
    false,
    false,
    true,
    true,
    445,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Bella Napoli'),
    'Tiramisu',
    'Classic Italian coffee-flavored dessert',
    6.99,
    'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9',
    'Dessert',
    5,
    450,
    true,
    false,
    false,
    false,
    true,
    true,
    534,
    NOW(),
    NOW()
);

-- Burger Paradise Menu
INSERT INTO menu_items (
    id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    category,
    preparation_time,
    calories,
    is_vegetarian,
    is_vegan,
    is_gluten_free,
    is_spicy,
    is_available,
    is_active,
    order_count,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Burger Paradise'),
    'Classic Cheeseburger',
    'Beef patty with cheddar cheese, lettuce, tomato and special sauce',
    11.99,
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    'Main Course',
    15,
    820,
    false,
    false,
    false,
    false,
    true,
    true,
    789,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Burger Paradise'),
    'Crispy Fries',
    'Golden French fries with sea salt',
    4.50,
    'https://images.unsplash.com/photo-1573080496219-bb080dd4f877',
    'Side Dish',
    8,
    420,
    true,
    true,
    true,
    false,
    true,
    true,
    892,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    (SELECT id FROM restaurants WHERE name = 'Burger Paradise'),
    'Chocolate Milkshake',
    'Thick and creamy chocolate milkshake',
    5.99,
    'https://images.unsplash.com/photo-1572490122747-3968b75cc699',
    'Beverage',
    5,
    380,
    true,
    false,
    true,
    false,
    true,
    true,
    667,
    NOW(),
    NOW()
);
